<?php
echo '<?php
    $title = \'Delete '.$this->name.'\';
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete this item?</p>

<?php
    $url = $this->url(\''.$this->route.'\', array(
        \'action\' => \'delete\',
        \'id\'     => $this->id,
    ));
?>

<form action="<?php echo $url; ?>" method="post">
    <div>
    <input type="hidden" name="id" value="<?php echo (int) $'.$this->route.'->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
    </div>
</form>';