<?php
echo '<?php

namespace '.$this->namespace.'\Controller;

use Zend\Mvc\Controller\AbstractActionController,
    Zend\View\Model\ViewModel,
    Doctrine\ORM\EntityManager,
    '.$this->namespace.'\Form\\'.$this->tableName.'Form,
    '.$this->namespace.'\Entity\\'.$this->tableName.';

class '.$this->namespace.'Controller extends AbstractActionController
{

    /**
    * @var Doctrine\ORM\EntityManager
    */
    protected $em;

    public function setEntityManager(EntityManager $em)
    {
        $this->em = $em;
    }

    public function getEntityManager()
    {
        if (null === $this->em) {
            $this->em = $this->getServiceLocator()->get(\''.$this->entityManager.'\');
        }
        return $this->em;
    }

    public function indexAction()
    {
        return new ViewModel(array(
            \''.strtolower($this->namespace).'\' => $this->getEntityManager()->getRepository(\''.$this->namespace.'\Entity\\'.$this->tableName.'\')->findAll()
        ));
    }

    public function addAction()
    {

        $form = new '.$this->tableName.'Form();
        $form->get(\'submit\')->setAttribute(\'label\', \'Add\');

        $request = $this->getRequest();
        if ($request->isPost()) {
            $entity = new '.$this->tableName.'();
            $form->setInputFilter($entity->getInputFilter());
            $form->setData($request->getPost());
            if ($form->isValid()) {

                $entity->populate($form->getData());
                $this->getEntityManager()->persist($entity);
                $this->getEntityManager()->flush();

                return $this->redirect()->toRoute(\''.strtolower($this->namespace).'\');
            }
        }

        return array(\'form\' => $form);
    }

    public function editAction()
    {
        $id = (int)$this->getEvent()->getRouteMatch()->getParam(\'id\');
        if (!$id) {
            return $this->redirect()->toRoute(\''.strtolower($this->namespace).'\', array(\'action\'=>\'add\'));
        }

        $entity = $this->getEntityManager()->find(\''.$this->namespace.'\Entity\\'.$this->tableName.'\', $id);

        $form = new '.$this->tableName.'Form();
        $form->setBindOnValidate(false);
        $form->bind($entity);
        $form->get(\'submit\')->setAttribute(\'label\', \'Edit\');

        $request = $this->getRequest();

        if ($request->isPost()) {
            $form->setData($request->getPost());
            if ($form->isValid()) {
                $form->bindValues();
                $this->getEntityManager()->flush();

                return $this->redirect()->toRoute(\''.strtolower($this->namespace).'\');
            }
        }

        return array(\'id\' => $id, \'form\' => $form,);
    }

    public function deleteAction()
    {
        $id = (int)$this->getEvent()->getRouteMatch()->getParam(\'id\');
        if (!$id) {
            return $this->redirect()->toRoute(\''.strtolower($this->namespace).'\');
        }

        $request = $this->getRequest();
        if ($request->isPost()) {

            $del = $request->getPost()->get(\'del\', \'No\');
            if ($del == \'Yes\') {

                $entity = $this->getEntityManager()->find(\''.$this->namespace.'\Entity\\'.$this->tableName.'\', $id);
                if ($entity) {
                    $this->getEntityManager()->remove($entity);
                    $this->getEntityManager()->flush();
                }
            }

            return $this->redirect()->toRoute(\''.strtolower($this->namespace).'\');
        }

        return array(\'id\' => $id,);
    }

}';